[package]
name = "vaabbit"

version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
debug = true

[profile.release.package."*"]
opt-level = 3


[dependencies]
anymap = "*"
glam = "*"
pulz-arena = "*"
smallvec = "1.15.1"
ulid = "*"

[dev-dependencies]
macroquad = "*"
vibbit = { path = "../vibbit" }
